### ISSUE TITLE
How to exclude or configure to only generate docs of the specific folder only?

### ISSUE THREAD

**Issue by millisami** [zipmark/rspec_api_documentation#100]
I've other tests in my `spec/acceptance` dir.
I am writing the api tests only in the `spec/acceptance/api` directory.
But when I run the `rake docs:generate` task, it tries to generate for all the `spec/acceptance/**/*_spec.rb` file as its the default.

How to configure it to only generate docs for the folder `spec/acceptance/api/**/*_spec.rb` files only?

**Comment by bellmyer** [comment]
The problem I found with running rspec on just one acceptance file with "--format RspecApiDocumentation::ApiFormatter" is that it removes the docs for all the other acceptance tests. This might not be an issue with vanilla RAD, but It's the case with the `apitome` gem that rolls everything into one nicely formatted page.

**Comment by oestrich** [comment]
You can also try the `append_json` format. That should leave everything in place and only update what changed.

**Comment by stwr667** [comment]
Here's a snippet I highly recommend:
e.g. in `lib/tasks/api_docs.rake`:
```ruby
require 'rspec/core/rake_task'

desc 'Generate API request documentation from API specs'
RSpec::Core::RakeTask.new('api_docs:generate') do |t|
  t.pattern = 'spec/acceptance/**/*_spec.rb'
  t.rspec_opts = ['--format RspecApiDocumentation::ApiFormatter --tag ~@document:false']
end
```
then run:
`RAILS_ENV=test rake api_docs:generate`

For us, this is way more efficient, purely because of the extra **--tag ~@document:false** rspec command line option. It basically skips all the tests that don't generate any documentation, when generating the documentation. For us, this brought the number of tests being executed to generate docs down from **195** to **37**. 

Come to think of it, I'm surprised it's not on by default!
