### ISSUE TITLE
keep_source_order is using test run order, not source order

### ISSUE THREAD

**Issue by zofrex** [zipmark/rspec_api_documentation#192]
I've set `config.keep_source_order = true` but my output is ordered by the order the tests run in, not the order they appear in the source code. Is this expected?

Edit: I have `config.order = "random"` in my RSpec configuration, that's probably important information.

**Comment by oestrich** [comment]
Looking at the source code I don't know if it ever kept the examples in the source order if rspec was running them in a random order. The only thing it does is not sort by description, [see here](https://github.com/zipmark/rspec_api_documentation/blob/master/lib/rspec_api_documentation/writers/index_helper.rb#L8).

I think the way around this is already built in. Can you try `rake docs:generate:ordered`? It sets the order to default, which should hopefully be the source order.

**Comment by indiesquidge** [comment]
@oestrich I am running into trouble with `rake docs:generate:ordered`. It seems to load the `doc/api/index.json` data in the same order that `rake docs:generate` does, which is to say alphabetically rather than based on the source, which is what I expected (unless I'm misinterpreting `ordered`).

I was trying to dig around the `rspec_api_documentation` source code for some indication as to what this line does for me.
```ruby
t.rspec_opts = ["--format RspecApiDocumentation::ApiFormatter", "--order default"]
```
What is `--order default`? Are there other ordering options? If so, how can I find them? How should I get the docs to match the order that the specs are written in? Any help would be greatly appreciated.

I know that most people create or comment on issues about stuff that is broken or that they don't like. Just know that I think this project is awesome, and I love the work you guys are doing on it. Keep it up! :smiley:

**Comment by oestrich** [comment]
@indiesquidge Glad I could help! Got everything working?

**Comment by indiesquidge** [comment]
Well, now I'm curious about the difference in these rake tasks. When I have `config.keep_source_order = true` set, that seems to make the difference in the order, not the rake task; `rake docs:generate` and `rake docs:generate:ordered` appear to do the exact same thing.

Let's say, hypothetically, that I would like to have both tasks working, where `rake docs:generate` orders them alphabetically (seems to be the default), and `rake docs:generate:ordered` orders them based on the source. How would I go about getting that?

I suppose it all comes back to that one line I mentioned in my first comment and what that line is even doing for me/how I can manipulate it to do something different.

**Comment by oestrich** [comment]
I think at one point we didn't order tests at all so the rspec `--order` mattered a lot. It probably happened around this line being changed https://github.com/zipmark/rspec_api_documentation/blob/3c2f23d7442defc326c6b8674ec614e9260bc7d8/lib/rspec_api_documentation/writers/index_helper.rb#L8

**Comment by indiesquidge** [comment]
Ah, I see. So at this point, the `--order` is kind of irrelevant since everything now depends on `config.keep_source_order`, is that correct? So it's a bit harder if I want to have rake tasks that will change the order now then, as I would have to set `config.keep_source_order` in the task, yeah?

**Comment by indiesquidge** [comment]
I was thinking I could just configure it in the rake task, like so
```ruby
desc 'Generate API request documentation from API specs'
RSpec::Core::RakeTask.new('docs:generate') do |t|
  RspecApiDocumentation.configure do |config|
    config.keep_source_order = false
  end
  t.pattern = 'spec/acceptance/**/*_spec.rb'
  t.rspec_opts = ["--format RspecApiDocumentation::ApiFormatter"]
end
```
and the respective `ordered` task as well
```ruby
desc 'Generate API request documentation from API specs'
RSpec::Core::RakeTask.new('docs:generate:ordered') do |t|
  RspecApiDocumentation.configure do |config|
    config.keep_source_order = true
  end
  t.pattern = 'spec/acceptance/**/*_spec.rb'
  t.rspec_opts = ["--format RspecApiDocumentation::ApiFormatter"]
end
```

But this doesn't seem to work. Its back to having `config.keep_source_order` set to false even if I set it to true in the rake task.

**Comment by davidstosik** [comment]
I've been facing the same problem. Multiple times, I thought I'd solved it after changing something in the way I generate the doc, but nothing works. Note that, as @zofrex, I have `config.order = "random"` in my RSpec configuration, and commenting the line fixes the problem (documentation is sorted as the source).

- setting `config.keep_source_order = true` does not work
- using `rake docs:generate:ordered` does not work (although the output shows that `--option default` was appended to the rspec command
- doing both above together didn't fix the problem either

Now checking RSpec documentation, problem is clear: the `--order` options changed: while old versions of RSpec will use `--order default` to run tests in the source order, more "recent" (3 and above?) versions use `--order defined`. ([See this commit on rspec-core repository.](https://github.com/rspec/rspec-core/commit/57ab90ad3369e38fb0e3425b0c39017f44ad8555))

I also confirmed that no backwards compatibility is assured by running `bin/rspec -fd --order default` on my local, which ran my tests in a random order (and also output the random seed at the end).

**Comment by davidstosik** [comment]
Quick workaround for people who don't want to wait a new version: copy the file `lib/tasks/docs.rake` in the PR above to your project's `lib/tasks` folder.

**Comment by davidstosik** [comment]
If I may, I'd like to detail what I understood, so that it's not lost.

- `keep_source_order = true` actually just means "Do not sort by description. Instead, the order in which tests were ran will be used (ie. if tests run in random order, result will be random too)." I'd suggest a rename, such as `sort_by_description`, with a default to `true`, for backwards compatibility.
- The difference between `rake docs:generate` and `rake docs:generate:ordered` is that the latter explicitly tries to tell rspec not to randomize the tests (`--order default` in old RSpec versions, but should be `--order defined` in recent versions, see PR #245 ).
- For some people, `rake docs:generate` will be sorted, for others it won't. It depends on their project's setup, and whether rspec was set to run tests randomly or not (my `spec_helper.rb` file contains `config.order = :random`, so I need to use `rake docs:generate:sorted` if I want to get a sorted documentation).
