### ISSUE TITLE
swagger support

### ISSUE THREAD

**Issue by ghost** [zipmark/rspec_api_documentation#216]
Hi,

Do You plan any support for swagger? I think this could increase popularity of gem :-)

**Comment by ceritium** [comment]
+1

**Comment by oestrich** [comment]
I will definitely accept a PR that adds support for swagger. I have no plans on adding it myself as I don't use it.

**Comment by ceritium** [comment]
Ok, I started, not too much because first I had to understood how the gem works.

Anyway, you can follow my progress here: https://github.com/zipmark/rspec_api_documentation/compare/master...ceritium:swagger?expand=1

I will continue on Monday, (holidays) . Also I hope introduce continue with this empowered for my company.

**Comment by galiat** [comment]
+1

**Comment by zoras** [comment]
+1

**Comment by sebweaver** [comment]
:+1:

**Comment by pklingem** [comment]
+1

**Comment by anklos** [comment]
+1

**Comment by terry90** [comment]
:raised_hands:

**Comment by djezzzl** [comment]
#347

**Comment by smarquez1** [comment]
@djezzzl I think this can be closed since https://github.com/zipmark/rspec_api_documentation/pull/347 has been merged. Thank you so much
